name: the_forge
description: "A private Android sports tracking application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
